# Generated by Django 2.1.5 on 2019-02-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='vid',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
