# Generated by Django 2.1.5 on 2019-02-08 17:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20190205_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
