# Generated by Django 2.1.5 on 2019-02-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20190208_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
