# Generated by Django 2.1.5 on 2019-02-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='upload',
            field=models.FileField(null=True, upload_to='my_video/'),
        ),
    ]
